### ISSUE TITLE
Files ready for usage

### ISSUE THREAD

**Issue by LostKobrakai** [jquery/PointerEvents#150] opened 2015-01-09 16:41 UTC
How about adding a build version of the polyfill to the repository. I find it quite annoying to fiddle around with all those node build scripts just to get a working copy of a js library. I ended up using the one from the gh-pages branch.

**Comment by roblarsen** [comment] 2015-01-09 16:46
this is a dupe of #140 which they closed and where they promised ready-to-use files of some sort.

**Closed** 2015-01-09 16:46 UTC
